### ISSUE TITLE
Peer review 2

### ISSUE THREAD

**Issue by vitoriapacela** [wood101/ChessAITiraLab#2]
# Peer-review 2
### General comments
- I downloaded the project around 16:00 on Friday (12/10/18).
- The project seems very interesting and the documentation is good.
  - The Design Document is very clear and concise, with good links for the understanding of the algorithms.
  - The Implementation document is a bit too short. For example, I believe that descriptions of what each class does could be useful, so that we have an overview of how they relate to each other and how your implementation functions.
  - The testing document contains the most relevant information regarding the analysis of your algorithm, it seems to be good. However, I am wondering if the AI always wins, or if it would be relevant to analyze the winning ratio. Furthermore, a description of the java tests could be useful too.

### Issues
- I had to rename all the packages to remove "java" from the name. eg: java.fi.helsinki.chessai -> fi.helsinki.chessai. I also could have done the other way around: changing the package defined in each file and its imports consistently, but I found such method more time consuming.
- Nothing works for me, which is a pity, because I was really interested in seeing this. The error is below:
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at fi.helsinki.chessai.Chess.main(Chess.java:15)
Caused by: java.lang.NullPointerException
	at fi.helsinki.chessai.gui.Table$TilePanel.assignTilePieceIcon(Table.java:439)
	at fi.helsinki.chessai.gui.Table$TilePanel.<init>(Table.java:329)
	at fi.helsinki.chessai.gui.Table$BoardPanel.<init>(Table.java:288)
	at fi.helsinki.chessai.gui.Table.<init>(Table.java:71)
	at fi.helsinki.chessai.gui.Table.<clinit>(Table.java:58)
	... 1 more
```
  Unfortunately I am not familiar enough with the code or with Java to debug this, so I had to stop there. Due to this problem, all of my tests are failing too.

**Comment by wood101** [comment]
You can try running this if you want to test the game:
[ChessAI-1.0.zip](https://github.com/wood101/ChessAITiraLab/files/2473750/ChessAI-1.0.zip)

It sounds like you had some sort of importing problem. The packages are not supposed to start with java.
